### ISSUE TITLE
400 Bad Request  respond from non default region

### ISSUE THREAD

**Issue by tal5ab** [rustyconover/net-amazon-s3#19] opened 2016-12-20 12:57 UTC
Hi
I am trying to download a file from few S3 buckets
Files from Location: US West (Oregon) (us-west-2)  works fine  (This is Amazone default region)
But when i try to get from Location: EU (Frankfurt) (eu-central-1) i get Amazon::S3: Amazon responded with 400 Bad Request

How do i tell this module my bucket is located in non default region?
There is no mention of this in the docs as far as i can see

my code
```
	my $s3 = Amazon::S3->new({
			aws_access_key_id     => $accessKey,
			aws_secret_access_key => $secret_access_key,
			retry                 => 1,
	});
		my $bucket = $s3->bucket($bucket_name);
		my $response = $bucket->get_key_filename($path_to_file,'GET',$destination_file) or die $s3->err . ": ". $s3->errstr;
```

**Comment by renatocron** [comment] 2016-12-20 13:05
When you create a new S3 client object, use argument *host*:
``` 
* host *
   The S3 host endpoint to use. Defaults to 's3.amazonaws.com'. 
   This allows you to connect to any S3-compatible host.
``` 


`Net::Amazon::S3->new( { host => 's3.ca-central-1.amazonaws.com' , aws_access_key_id...} )`

**Comment by tal5ab** [comment] 2016-12-20 13:22
Thank you for such a fast respond
But i tried all 3 possible EU URLs:
s3.eu-central-1.amazonaws.com
s3-eu-central-1.amazonaws.com
s3.dualstack.eu-central-1.amazonaws.com

```
	my $s3 = Amazon::S3->new({
			host				  => 's3.dualstack.eu-central-1.amazonaws.com',
			aws_access_key_id     => $accessKey,
			aws_secret_access_key => $secret_access_key,
			retry                 => 1,
	});
```
None of them worked 
Still getting 400

**Comment by renatocron** [comment] 2016-12-20 13:27
You are using `Amazon::S3`, not `Net::Amazon::S3`

I strongly recommend you to adapt your code to use Net::Amazon::S3 on version 0.80 (before this version, I can't recommend either!)

**Comment by tal5ab** [comment] 2016-12-21 07:25
```
	my $s3 = Net::Amazon::S3->new({
			host				  => 's3-eu-central-1.amazonaws.com',
			aws_access_key_id     => $accessKey,
			aws_secret_access_key => $secret_access_key,
			retry                 => 1,
	});

```
C:\Users\cuser>cpan install Net::Amazon::S3
Loading internal null logger. Install Log::Log4perl for logging messages
CPAN: CPAN::SQLite loaded ok (v0.211)
Database was generated on Tue, 20 Dec 2016 07:41:59 GMT

CPAN: Module::CoreList loaded ok (v5.20160121)
Net::Amazon::S3 is up to date (0.80).


but still i get 
Net::Amazon::S3: Amazon responded with 400 Bad Request
 at C:/Strawberry/perl/site/lib/Net/Amazon/S3/Bucket.pm line 151.

**Comment by Bu11etmagnet** [comment] 2016-12-23 13:04
's3-eu-central-1.amazonaws.com' seems wrong; have you tried 

's3.eu-central-1.amazonaws.com' ?



--

 

  grobbelaar@letterboxes.org



-- 
http://www.fastmail.com - A fast, anti-spam email service.

**Comment by rustyconover** [comment] 2016-12-27 13:33
The problem is the Frankfurt region uses AWS signatures version 4, I don't believe this module implements them, yet.

**Comment by ranguard** [comment] 2018-06-28 19:52
https://metacpan.org/release/LLAP/Net-Amazon-S3-0.81-TRIAL just released with V4 support - any testing you can do would be appreciated - please do open issue if you have any

**Closed by ranguard** 2018-06-28 19:52 UTC
